# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 642)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 80, 451, 61))
        self.label.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 210, 121, 21))
        self.label_2.setObjectName("label_2")
        self.txt_name = QtWidgets.QLineEdit(Form)
        self.txt_name.setGeometry(QtCore.QRect(250, 210, 113, 22))
        self.txt_name.setObjectName("txt_name")
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setGeometry(QtCore.QRect(180, 330, 141, 28))
        self.btn_start.setStyleSheet("font: 10pt \"MS Shell Dlg 2\"; background-color: rgb(85, 0, 255)")
        self.btn_start.setObjectName("btn_start")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome to Chat APP"))
        self.label_2.setText(_translate("Form", "Enter your name: "))
        self.btn_start.setText(_translate("Form", "Start you chat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
