# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'room.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtMultimediaWidgets import QVideoWidget, QGraphicsVideoItem
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QFileDialog, QGraphicsTextItem, QProgressBar, \
    QScrollArea, QWidget, QVBoxLayout
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt, QUrl
from PyQt5.QtWidgets import QGraphicsView, QGraphicsScene, QLabel, QGraphicsPixmapItem
import cv2
import numpy as np
from video import VideoPlayer
from audio import AudioPlayer

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 640)
        self.label = QLabel(Form)
        self.label.setGeometry(160, 50, 55, 16)
        self.label.setObjectName("label")
        self.label_2 = QLabel(Form)
        self.label_2.setGeometry(280, 50, 55, 16)
        self.label_2.setObjectName("label_2")
        self.text_message = QtWidgets.QTextEdit(Form)
        self.text_message.setGeometry(QtCore.QRect(110, 540, 241, 101))
        self.text_message.setObjectName("text_message")
        self.btn_sendText = QPushButton(Form)
        self.btn_sendText.setGeometry(360, 540, 93, 28)
        self.btn_sendText.setObjectName("btn_sendText")
        self.btn_send_muti = QPushButton(Form)
        self.btn_send_muti.setGeometry(10, 550, 93, 28)
        self.btn_send_muti.setObjectName("btn_send_muti")
        self.btn_send_folder = QPushButton(Form)
        self.btn_send_folder.setGeometry(10, 590, 93, 28)
        self.btn_send_folder.setObjectName("btn_send_folder")


        self.scroll_area = QScrollArea(Form)
        self.scroll_area.setGeometry(0, 90, 480, 450)
        self.scroll_area.setWidgetResizable(True)  # Đặt thuộc tính này thành True để tự động thích ứng kích thước
        self.content_widget = QWidget()
        self.scroll_area.setWidget(self.content_widget)

        self.content_layout = QVBoxLayout(self.content_widget)

        self.retranslateUi(Form)
        self.form = Form
        self.msgs = []
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.progress_bar = QProgressBar(self.form)
        self.progress_bar.setGeometry(370, 600, 120, 30)
        self.progress_bar.setMaximum(100)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ROOM"))
        self.label_2.setText(_translate("Form", "XXXX"))
        self.btn_sendText.setText(_translate("Form", "Send"))
        self.btn_send_muti.setText(_translate("Form", "Multimedia file"))
        self.btn_send_folder.setText(_translate("Form", "Folder"))

    def add_text_message(self, msg):
        label = QLabel(msg)
        self.content_layout.addWidget(label)



    def add_image_message(self, fr, file_name):
        # Đọc và hiển thị hình ảnh
        image = cv2.imread(file_name)
        height, width, channels = image.shape
        resized_image = cv2.resize(image, (400, int(height * 400 / width)))

        # Chuyển đổi từ định dạng BGR sang RGB (Qt sử dụng định dạng RGB)
        image_rgb = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB)

        # Tạo QPixmap từ hình ảnh OpenCV
        q_image = QPixmap.fromImage(QImage(image_rgb, image_rgb.shape[1], image_rgb.shape[0],
                                           image_rgb.strides[0], QImage.Format_RGB888))

        # Tạo QLabel và đặt hình ảnh vào đó
        text_label = QLabel(f"{fr} đã gửi một hình ảnh: ")
        self.content_layout.addWidget(text_label)
        label = QLabel()
        label.setPixmap(q_image)
        self.content_layout.addWidget(label)

    def add_video_message(self, fr, file_name):

        text_label = QLabel(f"{fr} đã gửi một video: ")
        self.content_layout.addWidget(text_label)

        video_widget = VideoPlayer(file_name)

        # Thêm video_view vào content layout
        self.content_layout.addWidget(video_widget)

    def add_audio_message(self, fr, file_name):
        audio_player = AudioPlayer(fr, file_name)
        self.content_layout.addWidget(audio_player)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


